# Generated by Django 2.2.1 on 2019-05-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, choices=[('beijing', '北京'), ('shanghai', '上海'), ('guangzhou', '广州'), ('shenzhen', '深圳')], max_length=200),
        ),
    ]
